name: Deploy Android
on:
  push:
    branches:
      - main
jobs:
  set-up-flutter:
    name: Setup Flutter
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.x'
          channel: 'stable'
      - run: flutter pub get
      - run: pub global activate grinder
      - run: flutter pub run build_runner build --delete-conflicting-outputs
