name: Deploy Android
on:
  push:
    branches:
      - main
jobs:
  setup-flutter:
    name: Setup Flutter
    runs-on: macos-latest
    steps:
      - name: Install Flutter
        uses: actions/checkout@v2.3.4
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.x'
          channel: 'stable'
      - name: Get package
        run: flutter pub get
      - name: Activate Grinder
        run: pub global activate grinder
      - name: Run build_runner
        run: flutter pub run build_runner build --delete-conflicting-outputs
  # setup-secrets:
  #   name: Setup secrets
  #   needs: [setup-flutter]
  #   runs-on: macos-latest
  #   steps:
  #     - name: Generate key.jks
  #       run:
