name: Deploy Android
on:
  push:
    branches:
      - main
jobs:
  setup-flutter:
    name: Setup Flutter
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '16.x'
      - name: Flutter action
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.x'
          channel: 'stable'
      - name: Get package
        run: flutter pub get
      - name: Activate Grinder
        run: pub global activate grinder
      - name: Run build_runner
        run: flutter pub run build_runner build --delete-conflicting-outputs
  setup-secrets:
    name: Setup secrets
    needs: [setup-flutter]
    runs-on: macos-latest
    steps:
      - name: Generate key.jks
        run: echo -n ${{ secrets.ANDROID_KEY_JKS }} | base64 -d > android/key.jks
      - name: Generate Service Account key
        run: echo -n ${{ secrets.SERVICE_ACCOUNT_KEY_JSON }} | base64 -d > android/service-account-key.json
      - name: Generate key.properties
        run: |
          echo 'storePassword=${{ secrets.ANDROID_STORE_PASSWORD }}' >> android/key.properties
          echo 'keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}' >> android/key.properties
          echo 'keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}' >> android/key.properties
          echo 'storeFile=key.jks' > android/key.properties
          echo 'serviceAccountFile=service-account-key.json' >> android/key.properties
  publish-to-store:
    name: Publish to store
    needs: [setup-secrets]
    runs-on: macos-latest
    steps:
      - name: Build Android App Bundle
        run: flutter build appbundle --flavor=prod --target=lib/main-prod.dart --build-number ${GITHUB_RUN_NUMBER}
      - name: Upload to store
        run: ./gradlew publishBundle
        working-directory: ./android
